### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by PanderMusubi** [pi3ch/ssh_anysoftkeyboard#2]
Please, add badges for Google Play and F-Droid as for example seen in https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/README.md

**Comment by PanderMusubi** [comment]
Fixed in https://github.com/pi3ch/ssh_anysoftkeyboard/pull/3

**Comment by pi3ch** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard

**Comment by PanderMusubi** [comment]
I think something went wrong with the link. Can you see what?
