### ISSUE TITLE
Marked as vulnerable in F-Droid

### ISSUE THREAD

**Issue by pchampin** [pi3ch/ssh_anysoftkeyboard#4]
I just updated F-Droid to version 1.0 and it altered me that a number of my installed packages, including the SSH package for ASK, were vulnerable.

More precisely, it has the KnownVul and DisabledAlgorithm tags, both described [here](https://f-droid.org/wiki/page/AntiFeature:KnownVuln). From what I understand, it is mostly a matter or re-packaging rather than re-coding anything...

**Comment by pi3ch** [comment]
The ownership of the package has been transferred to ASK team. Please check https://github.com/AnySoftKeyboard/AnySoftKeyboard
